apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["cluster-owner"],"required":["cluster-owner"]}'
    authz.management.cattle.io/initial-sync: "true"
    clusters.management.cattle.io/ke-last-refresh: "1749726466"
    field.cattle.io/creatorId: user-x5df2
    lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
    lifecycle.cattle.io/create.cluster-provisioner-controller: "true"
    lifecycle.cattle.io/create.cluster-scoped-gc: "true"
    lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
    provisioner.cattle.io/encrypt-migrated: "true"
  generateName: c-
  labels:
    cattle.io/creator: norman
    provider.cattle.io: gke
  name: c-5001g
spec:
  agentImageOverride: ""
  answers: {}
  clusterSecrets: {}
  description: ""
  desiredAgentImage: ""
  desiredAuthImage: ""
  displayName: rancher-lnp-5001
  dockerRootDir: /var/lib/docker
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  gkeConfig:
    clusterAddons:
      horizontalPodAutoscaling: true
      httpLoadBalancing: true
    clusterIpv4Cidr: 100.68.0.0/14
    clusterName: rancher-lnp-5001
    description: ""
    enableKubernetesAlpha: false
    googleCredentialSecret: cattle-global-data:cc-nnb6j
    imported: false
    ipAllocationPolicy:
      clusterIpv4CidrBlock: 100.68.0.0/14
      clusterSecondaryRangeName: dev52-test-apps-kubeio-argo-rollout-pod-0
      servicesIpv4CidrBlock: 100.66.0.0/17
      servicesSecondaryRangeName: dev52-test-apps-kubeio-argo-rollout-svc-0
      useIpAliases: true
    kubernetesVersion: 1.32.4-gke.1236007
    labels: {}
    locations:
    - us-central1-a
    loggingService: logging.googleapis.com/kubernetes
    maintenanceWindow: ""
    masterAuthorizedNetworks:
      cidrBlocks:
      - cidrBlock: 10.0.0.0/8
        displayName: testall
      enabled: true
    monitoringService: monitoring.googleapis.com/kubernetes
    network: us-central1-test-apps
    networkPolicyEnabled: false
    nodePools:
    - autoscaling: {}
      config:
        bootDiskKmsKey: projects/pp-d-dev-gce01-kms/locations/us-central1/keyRings/dev-pp-keyring-us-central1/cryptoKeys/dev-pp-vmenc-key-us-central1
        diskSizeGb: 100
        diskType: pd-balanced
        imageType: UBUNTU_CONTAINERD
        machineType: n2d-standard-8
        serviceAccount: lsvc-d-caas-kubeio@dev52-test-apps-kubeio.iam.gserviceaccount.com
      initialNodeCount: 1
      management:
        autoRepair: true
        autoUpgrade: true
      maxPodsConstraint: 32
      name: group-1
      version: 1.32.4-gke.1236007
    privateClusterConfig:
      enablePrivateEndpoint: true
      enablePrivateNodes: true
    projectID: dev52-test-apps-kubeio
    region: ""
    subnetwork: projects/pp-d-us-central1-xpn/regions/us-central1/subnetworks/dev52-us-central1-test-apps-2
    zone: us-central1-a
  internal: false
  localClusterAuthEndpoint:
    enabled: false
  windowsPreferedCluster: false
